version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/certgen"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
