version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/src/certbox"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/desktop"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@fontsource/fira-sans"
      - dependency-name: "@fortawesome/*"
      - dependency-name: "@types/*"
      - dependency-name: "@typescript-eslint/*"
      - dependency-name: "eslint-plugin-react"
      - dependency-name: "eslint-webpack-plugin"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@fontsource/fira-sans"
      - dependency-name: "@fortawesome/*"
      - dependency-name: "@types/*"
      - dependency-name: "@typescript-eslint/*"
      - dependency-name: "eslint-plugin-react"
      - dependency-name: "eslint-webpack-plugin"
      - dependency-name: "eslint"
