version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/src/certbox"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/desktop"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
