name: Desktop

on:
  push:
    paths:
      - '.github/workflows/desktop.yml'
  pull_request:
    paths:
      - 'src/desktop/**'
      - 'src/frontend/**'

permissions:
  contents: read

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #pin v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #pin v5.0.2
        with:
          go-version: "stable"
          cache-dependency-path: src/certbox/go.sum

      - name: Build certgen
        run: ./build.sh
        working-directory: src/certbox/cmd/certgen

      - name: Build app
        run: |
          npm i
          node start_webpack.js --mode production
          node build.linux.js
        working-directory: src/desktop

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 #pin v4.4.0
        with:
          name: certbox_linux
          path: package/artifacts/certbox_linux_*.tar.gz
          compression-level: 0

  build_macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #pin v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #pin v5.0.2
        with:
          go-version: "stable"
          cache-dependency-path: src/certbox/go.sum

      - name: Build certgen
        run: ./build.sh
        working-directory: src/certbox/cmd/certgen

      - name: Build app
        run: |
          npm i
          node start_webpack.js --mode production
          node build.darwin.js
        working-directory: src/desktop

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 #pin v4.4.0
        with:
          name: certbox_macos
          path: package/artifacts/certbox_macOS_*.dmg
          compression-level: 0

  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #pin v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #pin v5.0.2
        with:
          go-version: "stable"
          cache-dependency-path: src\certbox\go.sum

      - name: Build certgen
        run: .\build.cmd
        working-directory: src\certbox\cmd\certgen

      - name: Build app
        run: |
          npm i
          node start_webpack.js --mode production
          node build.windows.js
        working-directory: src\desktop

      - uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 #pin v4.4.0
        with:
          name: certbox_windows
          path: package/artifacts/certbox_windows_*.exe
          compression-level: 0
