name: Desktop

on:
  push:
    paths:
      - '.github/workflows/desktop.yml'
      - 'src/certbox/**'
      - 'src/desktop/**'
      - 'src/frontend/**'
  pull_request:
    paths:
      - '.github/workflows/desktop.yml'
      - 'src/certbox/**'
      - 'src/desktop/**'
      - 'src/frontend/**'

permissions:
  contents: read

jobs:
  build_linux_x64:
    name: Build Linux x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #pin v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: src/certbox/go.sum

      - name: Build app
        run: |
          node release.js
        env:
          DOCKER: docker
        working-directory: src/desktop

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: certbox_linux_x64
          path: |
            src/desktop/package/artifacts/certbox_linux_x64*.tar.gz
            src/desktop/package/artifacts/certbox-*_x64.deb
            src/desktop/package/artifacts/certbox-*.x86_64.rpm
          compression-level: 0

  build_linux_arm64:
    name: Build Linux ARM64
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #pin v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: src/certbox/go.sum

      - name: Build app
        run: |
          node release.js
        env:
          DOCKER: docker
        working-directory: src/desktop
  
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: certbox_linux_arm64
          path: |
            src/desktop/package/artifacts/certbox_linux_arm64*.tar.gz
            src/desktop/package/artifacts/certbox-*_arm64.deb
            src/desktop/package/artifacts/certbox-*.aarch64.rpm
          compression-level: 0

  build_macos:
    name: Build macOS Universal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #pin v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: src/certbox/go.sum

      - name: Build app
        run: |
          node release.js
        working-directory: src/desktop

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: certbox_macos_x64
          path: src/desktop/package/artifacts/certbox_macOS_x64.dmg
          compression-level: 0

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: certbox_macos_arm64
          path: src/desktop/package/artifacts/certbox_macOS_arm64.dmg
          compression-level: 0

  build_windows:
    name: Build Windows Universal
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #pin v5.5.0
        with:
          go-version: "stable"
          cache-dependency-path: src\certbox\go.sum

      - name: Build app
        run: |
          node release.js
        working-directory: src/desktop

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: certbox_windows_x64
          path: src/desktop/package/artifacts/certbox_windows_x64.exe
          compression-level: 0

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #pin v4.6.2
        with:
          name: certbox_windows_arm64
          path: src/desktop/package/artifacts/certbox_windows_arm64.exe
          compression-level: 0
