name: Go

on:
  push:
    paths:
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'src/certbox/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 #pin v5.3.0
        with:
          go-version: "stable"

      - name: Build
        run: go build -v ./...
        working-directory: src/certbox

      - name: Test
        run: go test -v ./...
        working-directory: src/certbox
