name: Go

on:
  push:
    paths:
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'src/certbox/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build
        run: go build -v ./...
        working-directory: src/certbox

      - name: Test
        run: go test -v ./...
        working-directory: src/certbox
