name: Go

on:
  push:
    paths:
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'src/certbox/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #pin v4.1.2

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #pin v5.0.0
        with:
          go-version: "1.22"

      - name: Build
        run: go build -v ./...
        working-directory: src/certbox

      - name: Test
        run: go test -v ./...
        working-directory: src/certbox
