name: Go

on:
  push:
    paths:
      - '.github/workflows/go.yml'
  pull_request:
    paths:
      - 'src/certbox/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #pin v4.2.2
        with:
          persist-credentials: false

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 #pin v5.5.0
        with:
          go-version: "stable"

      - name: Build
        run: go build -v ./...
        working-directory: src/certbox

      - name: Test
        run: go test -v ./...
        working-directory: src/certbox
