name: Web

on:
  push:
    paths:
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'src/web/**'
      - 'src/frontend/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 #pin v4.1.6

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 #pin v5.0.1
        with:
          go-version: "1.22"
          cache-dependency-path: src/certbox/go.sum

      - name: Build certgen
        run: ./wasm.sh
        working-directory: src/certbox/cmd/certgen

      - name: Build app
        run: |
          npm i
          npx webpack --config webpack.js --mode production
        working-directory: src/web
