name: Web

on:
  push:
    paths:
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'src/web/**'
      - 'src/frontend/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f #pin v4.1.3

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 #pin v5.0.0
        with:
          go-version: "1.22"
          cache-dependency-path: src/certbox/go.sum

      - name: Build certgen
        run: ./wasm.sh
        working-directory: src/certbox/cmd/certgen

      - name: Build app
        run: |
          npm i
          npx webpack --config webpack.js --mode production
        working-directory: src/web
