name: Web

on:
  push:
    paths:
      - '.github/workflows/web.yml'
  pull_request:
    paths:
      - 'src/web/**'
      - 'src/frontend/**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 #pin v4.1.7

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 #pin v5.0.2
        with:
          go-version: "stable"
          cache-dependency-path: src/certbox/go.sum

      - name: Build certgen
        run: ./wasm.sh
        working-directory: src/certbox/cmd/certgen

      - name: Build app
        run: |
          npm i
          npx webpack --config webpack.js --mode production
        working-directory: src/web
